name: Deploy Workflow for React App

on:
  workflow_run:
    workflows: ["Build Workflow for React App"]
    branches:
      - main

jobs:
  deploy:
    name: Deploy the React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy the React App
        run: |
          npm run build
          npm install -g gh-pages
          gh-pages -d build
